First PR
jfrog/jfrog-docker-desktop-extension pull request #26
Opened 2022-04-19 05:49 UTC by asafgabai

2022-05-09 09:24 UTC, eyalbe4 requested changes

2022-05-09 09:24 UTC, eyalbe4 commented on client/src/api/setup-env.ts
> + * Setups a new JFrog environment. It opens a registration form in a browser window and saves the environments details in the configuration.
Setups --> Sets up

2022-05-09 09:24 UTC, eyalbe4 commented on client/src/api/utils.ts
> +export async function getVersions(): Promise<Versions> {
Does this function return two versions? Which version is the first and which is the second? I suggest considering to modify the return value in a way that will make it clearer, or at least explain this as part of the description.

2022-05-10 06:52 UTC, asafgabai commented on client/src/api/config.ts
> + * If password or access token is not provided, then JfrogCliConfig is ignored and won't be saved (even if other properties were changed).
I was also wondering if it should be 'is' or 'are', so I googled it, and it turns out that it should be 'is' in this case.

2022-05-10 08:48 UTC, merged